# Generated by Django 4.2.10 on 2024-02-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestProduct',
        ),
    ]
